version: "3.5"

services:
  caddy:
    image: caddy:2.4.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  auth:
    build: ./auth
    expose:
      - "3003"
  mediaserver:
    build: ./mediasoup
    
  mongo:
    image: 'mongo'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rout
      MONGO_INITDB_ROOT_PASSWORD: bajskorv 
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./mongo-data:/data/db
    ports: 
      - 27017:27017
  mongo-admin:
    image: mongo-express
    depends_on: 
      - mongo
    ports: 
      - 8081:8081
    environment: 
      # ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017"
      ME_CONFIG_MONGODB_ADMINUSERNAME: rout
      ME_CONFIG_MONGODB_ADMINPASSWORD: bajskorv
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      # - ME_CONFIG_MONGODB_AUTH_DATABASE=admin